alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias py python
alias add "git add"
alias checkout "git checkout"
alias clone "git clone"
alias commit "git commit -S"
alias pull "git pull"
alias push "git push"
alias stat "git status"